{
 "title": "Prusa General Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Number of printers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count (prusa_up)", "legendFormat": "{{printer_model}}" }
   ]
  },
  {
   "title": "Number of printers offline",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count (prusa_up== 0) ", "legendFormat": "{{printer_model}}" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (prusa_up) by (printer_model)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Printers status",
   "type": "table",
   "gridPos": { "h": 19, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "max by (printer_name, printer_model, printer_address)(prusa_status_info) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Printer status",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 14, "w": 5, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "max by (printer_name,printer_state)(prusa_status_info)",
     "legendFormat": "{{printer_name}}"
    }
   ]
  },
  {
   "title": "Printer Online",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 14, "w": 6, "x": 5, "y": 5 },
   "targets": [
    {
     "expr": "max by (printer_name)(prusa_up)",
     "legendFormat": "{{printer_name}}"
    }
   ]
  },
  {
   "title": "G-Code for UDP sent",
   "type": "grafana-polystat-panel",
   "description": "There was an error while sending metrics activation G-Code to the printer OR it's deactivated ",
   "gridPos": { "h": 14, "w": 5, "x": 11, "y": 5 },
   "targets": [
    {
     "expr": "max by (printer_name,printer_state)(prusa_udp_metrics_gcode_sent)",
     "legendFormat": "{{printer_name}}"
    }
   ]
  }
 ]
}